from tests.test_files.test_read_gjf import _test_read_gjf
from tests.test_files.test_read_int import _test_int
from tests.test_files.test_read_wfn import _test_read_wfn, _test_molecular_orbitals
from tests.test_atoms import _test_atoms_coords