from ichor.cli.main_menu_submenus.analysis_menu.analysis_menu import ANALYSIS_MENU_DESCRIPTION
from ichor.cli.main_menu_submenus.molecular_dynamics_menu.molecular_dynamics_menu import MOLECULAR_DYNAMICS_MENU_DESCRIPTION
from ichor.cli.main_menu_submenus.points_directory_menu.points_directory_menu import POINTS_DIRECTORY_MENU_DESCRIPTION
from ichor.cli.main_menu_submenus.tools_menu.tools_menu import TOOLS_MENU_DESCRIPTION